services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: terralab
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: terralab
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    build: .
    depends_on:
      - postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://terralab:senha@postgres/terralab
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: bash -c "airflow db migrate && (airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin || true) && airflow webserver"

  scheduler:
    build: .
    depends_on:
      - postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://terralab:senha@postgres/terralab
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: scheduler

  dash_app:
    build:
      context: .
      dockerfile: Dockerfile.dash
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
    ports:
      - "8050:8050"
    volumes:
      - ./dags:/app/dags
    restart: unless-stopped

volumes:
  postgres_data:
