# Imagem base do Python
FROM python:3.11-slim

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia o arquivo de dependências
COPY requirements.txt .

# Instala as dependências Python
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo o código da aplicação
COPY app.py .
COPY dags/BR_UF_2024.geojson ./dags/

# Expõe a porta 8050 (padrão do Dash)
EXPOSE 8050

# Comando para iniciar a aplicação
CMD ["python", "app.py"]
